version: '2.2'
services:
  yellowcar:
    build:
      context: ./
      dockerfile: Dockerfile
    image: holaweb
    ports:
      - 8080-8090:8080
    networks:
      - network1
    scale: 3
 
networks:
  network1:
